apiVersion: v1
kind: ReplicationController
metadata:
	name: frontend-rc
spec:
	replicas: 3
	selector: 
		tier: frontend
	template: 
		metadata:
			labels:
				tier: frontend
		spec: 
			container:
			- name: apache
				image: httpd
				ports: 
				- containerPort: 80 