apiVersion: v1
kind: Pod
metadata: 
	name: web
spec:
	containers:
	- name: nginx
		image: nginx
		ports:
		- containerPort: 80
	- name: database
		image: postgres
		volumeMounts:
		-name: postgres-storage
			mountPath: /data/storage
	volumes:
	-name: postgres-storage
		emptyDir: {}
